import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import dynamic from "next/dynamic";
import { ChangeEvent, FormEvent, useCallback, useEffect, useMemo, useState } from 'react'
import { Header } from '../components/Header'
import styles from '../styles/Home.module.css'
import { Data } from './api/saved_results'

const Result = dynamic(() => import("../components/Result"), { ssr: false });

const History: NextPage = () => {
  const [result, setResult] = useState<Data | null>(null);
  const [currentKey, setCurrentKey] = useState<string | null>(null);

  useEffect(() => {
    window.fetch('/api/saved_results')
      .then(res => res.json())
      .then(json => {
        setResult(json);
      })
      .catch(error => {
        setResult({
          error: {
            message: error.message
          }
        })
      });
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>twitfreq</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/>
      <main className={styles.main}>
        <h3 className={styles.title}>
          流行チェッカー 履歴
        </h3>

        {result?.data ? (
          <ul>
            {Object.keys(result.data).map(key => {
              return <li key={key}>
                <a href="#" onClick={() => setCurrentKey(key)}>{key}</a>
              </li>
            })}
          </ul>
        ) : (
          '履歴はありません'
        )}

        <h3>「{currentKey}」の結果</h3>
        {currentKey && <Result data={result?.data?.[currentKey]} />}
      </main>
    </div>
  )
}

export default History
